alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy

controller:
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 4Gi

rbac:
  create: false

serviceAccount:
  create: true
  name: alloy

extraObjects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: alloy
    rules:
      - apiGroups: [""]
        resources: ["pods", "pods/log", "namespaces", "services", "endpoints", "events", "configmaps", "secrets", "nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["apps"]
        resources: ["replicasets"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["monitoring.coreos.com"]
        resources: ["servicemonitors"]
        verbs: ["get", "list", "watch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: alloy
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: alloy
    subjects:
      - kind: ServiceAccount
        name: alloy
        namespace: logging